api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "volume-discount"
type = "function"
uid = "bb2f00de-e779-90e3-7141-d67d5d765661b27f22c4"
description = "t:description"

  [[extensions.targeting]]
  target = "purchase.product-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/app/volume-discount/new"
  details = "/app/volume-discount/:id"
